### PR TITLE
Roster aplhabetical sorting

### PR DESCRIPTION
**Pull request by unam3**
https://github.com/ForNeVeR/kaiwa/issues/39

если сможешь смержить - последний коммит используй. хипстерхаб не умеет в пулреквесты из compare view. так бы сделал из https://github.com/ForNeVeR/kaiwa/compare/e3480c4...2189a5a

### CODE REVIEW

**Comment by ForNeVeR** [comment]
You also seems to be fixed #17, thank you.

**Comment by ForNeVeR** [comment]
@vitalyster, @oxpa, @hi-q, here we have the PR that will disable the status sort and enable only alphabet sort.

What would you say? Should I approve it or not? In #39 you expressed different opinions on that: @oxpa wanted alphabet sort only while @hi-q wanted to leave an optional status sort.

Personally I would prefer status _filter_ (there are no issue for that currently) and only an alphabet sort, so I give voice to merge that.

**Comment by vitalyster** [comment]
@ForNeVeR +1

**Comment by ForNeVeR** [comment]
Merged: f3ecf49068adf853c5827f103349bbcaf2ba98a1.

**Pull request closed without merging**
