### PR TITLE
Feature/react

### PR DESCRIPTION
**Pull request by Robbilie**
never ending pr

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I've tried to merge that, but had some problems around `config.js`. In the current setup, `server.js` keeps complaining about `window.SERVER_CONFIG = ...`, because is have no `window`. I've tried to remove that `window` and the whole assignment, but with no luck.

So, first of all, we need to fix the mess with config and set up some reliable way of tuning the app configuration. I'll merge that PR to temporary branch and play with the code a bit to invent a solution.

**Comment by Robbilie** [comment]
not sure why exactly but my server.js looks a bit different than the one in your branch:
https://github.com/Robbilie/kaiwa/blob/develop/src/server.js

**Comment by ForNeVeR** [comment]
But you've changed it yourself in scope of this PR: https://github.com/ForNeVeR/kaiwa/pull/130/files#diff-e6a5b42b2f7a26c840607370aed5301aL13

Nevermind, I think I know the solution. We will use [webpack define plugin](https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin) to manipulate the configuration and expose its parts to client. I'll fix the current troubles and proceed with merging PR.

**Comment by Robbilie** [comment]
i think i just didnt update the default config file, i think i have a if stmt checking if window is set, otherwise module.exports, have the code at home, will check later

**Comment by Robbilie** [comment]
smthng like this:

```
const config = {};
if(typeof(window) !== "undefined")
    window.SERVER_CONFIG = config;
else
    module.exports = { SERVER_CONFIG: config };
```

**Comment by ForNeVeR** [comment]
Thanks, I've rebased all your commits on top of the current `feature/react` branch. Please don't forget to update your config! I hope it'll be the last time; I have no plans to update its format again.

**Pull request closed without merging**
