### PR TITLE
docker files for kaiwa!

### PR DESCRIPTION
**Pull request by albjeremias**

### CODE REVIEW

**Review by ForNeVeR — APPROVED** [review]

**Comment by ForNeVeR** [comment]
We removed the original Dockerfile because it tried to manage LDAP. I am okay with Dockerfile in general. Also, I don't think we need it as a data volume, it doesn't seem right: usually the application code is baked into the image. Looks like this Dockerfile does everything right.

**Comment by ForNeVeR** [comment]
I think we'll use that for now, it's a step forward.

**Comment by albjeremias** [comment]
i want to develop! :) and I use docker to setup my environment, before developing! ;) docker is important, for helping developers and also for easy deployment even though the app should not be dependent on docker for deployment \o/

**Comment by ForNeVeR** [comment]
Yes, @albjeremias, thank you for your contribution. 👍

**Pull request merged**
