### PR TITLE
Develop docker

### PR DESCRIPTION
**Pull request by albjeremias**
:)))

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Honestly the `develop` branch is a bit abandoned for now, so you shouldn't try to use it. Although, I'll clean up the mess there a bit now and merge your Dockerfile change there, thanks. Gimme a couple of minutes.

**Comment by albjeremias** [comment]
but but... i like webpack :o u would need to refactor everything to typescript? also the package.json seems more up to date...

**Comment by vitalyster** [comment]
there is nots branch which is up to date with develop but without typescript :)

**Comment by ForNeVeR** [comment]
Unfortunately, `develop` branch doesn't work now. It is my never-ending try to rewrite whole application in React + Redux, and **nothing** works there properly.

Probably you could try to migrate webpack configuration from the `develop` branch to `master`. In case you'll be able to make it work, I would accept the pull request to the `master` branch.

**Comment by ForNeVeR** [comment]
I have merged/cherry-picked the Docker-related commits to the `develop` branch manually, so I close this PR.

**Comment by albjeremias** [comment]
cool!

**Pull request closed without merging**
